name: C CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Permissions
      working-directory: .
      run: chmod -R 777 lib
    - name: makeBuild
      working-directory: .
      run: mkdir build
    - name: CMake generation
      working-directory: .
      run: cd build && cmake ..
      shell: bash
      env:
       CC: clang
       CXX: clang
    - name: Compilation
      working-directory: .
      run: cd lib && ls && cd .. && cd build && make
      shell: bash
      env:
       CC: clang
       CXX: clang
    - name: runTests
      working-directory: .
      run: cd build && ctest -V
